### ISSUE TITLE
Support Arduino OPL2 (OPL3) communication protocol.

### ISSUE THREAD

**Issue by denjhang** [danielrfry/opl2sd1#12]
If it can support this, then I can easily use OPL3BankEditor to debug the YMF825 sound.
![截图未命名0410211006](https://user-images.githubusercontent.com/61811583/230907483-dc0f857d-74e1-4c99-9057-18e8c1f26a43.jpeg)
![截图未命名0410210811](https://user-images.githubusercontent.com/61811583/230907489-11b08a5a-0224-4a20-846f-7d7d2d441e87.jpeg)

**Comment by denjhang** [comment]
https://github.com/DhrBaksteen/ArduinoOPL2

**Comment by danielrfry** [comment]
Current development builds of OPL3BankEditor support the RetroWave OPL3 protocol, so it can already be used with `opl2sd1`.
