### ISSUE TITLE
Use stereo to play mono OPL2/3 music

### ISSUE THREAD

**Issue by denjhang** [danielrfry/opl2sd1#21]
This is a novel idea, derived from the OPLL chip of the in_vgm playback plug-in.
![截图未命名0430211451](https://user-images.githubusercontent.com/61811583/235354816-c2ff0d34-4cbe-4a7f-bf66-14afce5bb0cf.jpeg)

I hope to be able to manually specify the stereo position of each channel, only need to meet the simple stereo (just like OPL3 stereo, only L, M, R), such as:
ch1->R
ch2->L
ch3->M

**Comment by danielrfry** [comment]
I think this feature is out of scope of this project, but would be a good suggestion for a VGM player project instead - that way, it could potentially be used with other OPL compatible hardware and emulators as well.
